### PR TITLE
ci: build pypy wheels

### PR DESCRIPTION
**Pull request by adriangb**

### CODE REVIEW

**Comment by messense** [comment]
FYI: PyPy doesn't work on Apple Silicon Macs right now, no need to build universal2 wheels for it.

1. https://www.pypy.org/posts/2020/12/mac-meets-arm64-940822335619099039.html
2. https://foss.heptapod.net/pypy/pypy/-/issues/3566

**Comment by adriangb** [comment]
Gotcha, thanks. I originally [threw the entire matrix at it](https://github.com/adriangb/graphlib2/pull/7/commits/e89eb7c0b29083feae083f0fa478679bbd2dfddf) but got a lot of failures (mostly because of the glob installing the wrong wheel) so yeah my plan is to build PyPy 3.7, PyPy 3.8, etc. on each platform/arch. Aside from MacOS Universal wheels, are there any other combinations of platform/arch that I should be aware of not working with PyPy?

**Comment by messense** [comment]
> Aside from MacOS Universal wheels, are there any other combinations of platform/arch that I should be aware of not working with PyPy?

I think it works for macOS, Windows and Linux, we can even cross compile pypy wheels for aarch64 Linux.

**Comment by adriangb** [comment]
Awesome, thanks for your help. I'm away from keyboard for the next couple hours, but it looks like my setup pairing the Python versions and wheel glob worked, so I'll expand that to the rest of the platforms/arches later.

**Pull request closed without merging**
