### PR TITLE
rename internal package

### PR DESCRIPTION
**Pull request by adriangb**

### CODE REVIEW

**Comment by adriangb** [comment]
Hi @messense , sorry to bother you, do you see any obvious reason why this would be failing in CI? It runs for me locally even after a `git clean -fdx`.

**Comment by messense** [comment]
I think it's because Python try to import the local one first, see https://github.com/PyO3/maturin/issues/490.

I'd keep the `python/` folder to avoid such problem, the internal module rename should be fine.

**Comment by messense** [comment]
It's the exact reason we changed the default template to include a `python` folder in https://github.com/PyO3/maturin/pull/855

**Comment by adriangb** [comment]
Thanks yeah that's why I originally switched the layout

**Comment by messense** [comment]
We haven't implement reading maturin version from `pyproject.toml` in `maturin-action` yet, so you need to specify it manually:

```yaml
- uses: messense/maturin-action@v1
  with:
    maturin-version:v0.13.0-beta.6
```

**Comment by messense** [comment]
There were some breaking changes in v0.13, `--no-sdist` is replaced by `--dist`, see https://github.com/PyO3/maturin/pull/955

**Comment by adriangb** [comment]
Thank you @messense !

**Pull request merged**
